#!/bin/bash

NAME="numberdb"
DIR=/home/numberdb/numberdb-website/
USER=numberdb
GROUP=numberdb
WORKERS=2
BIND=unix:/home/numberdb/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=numberdb.settings
DJANGO_WSGI_MODULE=numberdb.wsgi
LOG_LEVEL=error

cd $DIR
#Don't use venv, rather use gunicorn that is installed in sage.
#source ../../venv/bin/activate

alias python="/home/numberdb/SageMath/local/bin/sage-python"
alias python3="/home/numberdb/SageMath/local/bin/sage-python"
alias python3.8="/home/numberdb/SageMath/local/bin/sage-python"

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec /home/numberdb/SageMath/local/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=- \
  --limit-request-line 0 \
  --limit-request-fields 100 \
  --limit-request-field_size 65536
