# Generated by Django 3.1.5 on 2021-01-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_delete_numberapprox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number_blob',
            field=models.BinaryField(db_index=True, max_length=16),
        ),
    ]
