# Generated by Django 3.1.5 on 2021-02-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20210209_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='collection',
        ),
    ]
