# Generated by Django 3.1.5 on 2021-01-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20210129_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtermvalue',
            name='value',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
