# Generated by Django 3.1.5 on 2021-01-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210130_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtermvalue',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
