# Generated by Django 3.1.5 on 2021-02-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_remove_number_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='db.collection'),
            preserve_default=False,
        ),
    ]
