# Generated by Django 3.1.5 on 2021-02-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_number_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='lower',
            field=models.FloatField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='number',
            name='upper',
            field=models.FloatField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
