# Generated by Django 3.1.5 on 2021-02-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20210130_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiondata',
            name='raw_yaml',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_lowercase',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
