# Generated by Django 3.1.5 on 2021-02-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20210209_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number_blob',
            field=models.BinaryField(db_index=True, max_length=16),
        ),
    ]
