# Generated by Django 3.1.5 on 2021-02-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20210209_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='frac_lower',
            field=models.FloatField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='number',
            name='frac_upper',
            field=models.FloatField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
