# Generated by Django 3.1.5 on 2021-02-09 22:33

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20210209_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField()),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.collection')),
            ],
        ),
    ]
