# Generated by Django 3.1.5 on 2021-02-09 22:35

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_collectionsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(default=''),
            preserve_default=False,
        ),
    ]
