# Generated by Django 3.1.5 on 2021-02-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_tag_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsearch',
            name='weight_A_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collectionsearch',
            name='weight_B_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collectionsearch',
            name='weight_C_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collectionsearch',
            name='weight_D_text',
            field=models.TextField(default=''),
        ),
    ]
