# Generated by Django 3.1.5 on 2021-02-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20210210_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='OeisNumber',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OeisSequence',
            fields=[
                ('a_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('numbers', models.ManyToManyField(related_name='sequences', to='db.OeisNumber')),
            ],
        ),
    ]
