# Generated by Django 3.1.5 on 2021-02-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_oeisnumber_oeissequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeisnumber',
            name='sequence_count',
            field=models.IntegerField(default=0),
        ),
    ]
