# Generated by Django 3.1.5 on 2021-05-06 09:14

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OeisNumber',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sequence_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tid', models.CharField(db_index=True, max_length=10, unique=True)),
                ('tid_int', models.IntegerField(db_index=True, default=0, primary_key=True, serialize=False)),
                ('url', models.CharField(db_index=True, max_length=256, unique=True)),
                ('path', models.CharField(db_index=True, max_length=512, unique=True)),
                ('title', models.CharField(db_index=True, max_length=256, unique=True)),
                ('title_lowercase', models.CharField(db_index=True, default='', max_length=256)),
                ('number_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name_lowercase', models.CharField(db_index=True, max_length=32)),
                ('table_count', models.IntegerField(default=0)),
                ('number_count', models.IntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField()),
            ],
        ),
        migrations.CreateModel(
            name='WikipediaNumber',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_A_text', models.TextField(default='')),
                ('weight_B_text', models.TextField(default='')),
                ('weight_C_text', models.TextField(default='')),
                ('weight_D_text', models.TextField(default='')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField()),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='db.table')),
            ],
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(default=dict)),
                ('raw_yaml', models.TextField(default='')),
                ('full_yaml', models.TextField(default='')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='db.table')),
            ],
        ),
        migrations.CreateModel(
            name='TableCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hexsha', models.CharField(db_index=True, max_length=40, unique=True)),
                ('author', models.CharField(db_index=True, max_length=200)),
                ('author_email', models.EmailField(db_index=True, max_length=254)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('timezone', models.IntegerField(default=0)),
                ('summary', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='')),
                ('tables', models.ManyToManyField(related_name='commits', to='db.Table')),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='tags',
            field=models.ManyToManyField(related_name='tables', to='db.Tag'),
        ),
        migrations.CreateModel(
            name='OeisSequence',
            fields=[
                ('a_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('numbers', models.ManyToManyField(related_name='sequences', to='db.OeisNumber')),
            ],
        ),
        migrations.CreateModel(
            name='NumberPAdic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_type', models.BinaryField(default=b'p', max_length=1)),
                ('number_string', models.TextField(db_index=True)),
                ('prime', models.IntegerField(db_index=True)),
                ('valuation', models.IntegerField(db_index=True)),
                ('param', models.BinaryField(max_length=16)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_adic_numbers', to='db.table')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_type', models.BinaryField(default=b'r', max_length=1)),
                ('number_blob', models.BinaryField(db_index=True, max_length=16)),
                ('lower', models.FloatField(db_index=True)),
                ('upper', models.FloatField(db_index=True)),
                ('frac_lower', models.FloatField(db_index=True)),
                ('frac_upper', models.FloatField(db_index=True)),
                ('param', models.BinaryField(max_length=16)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='db.table')),
            ],
        ),
    ]
