# Generated by Django 3.1.5 on 2021-05-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20210506_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='param',
            field=models.BinaryField(db_index=True, max_length=24),
        ),
    ]
