# Generated by Django 3.1.5 on 2021-05-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20210506_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberpadic',
            name='param',
            field=models.BinaryField(db_index=True, max_length=24),
        ),
    ]
