# Generated by Django 3.1.5 on 2021-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210506_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='param',
            field=models.BinaryField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='numberpadic',
            name='param',
            field=models.BinaryField(db_index=True, max_length=32),
        ),
    ]
