# Generated by Django 3.1.5 on 2021-05-09 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20210506_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_type', models.BinaryField(default=b'c', max_length=1)),
                ('number_searchstring', models.TextField(db_index=True, max_length=32)),
                ('param', models.BinaryField(db_index=True, max_length=32)),
                ('re_lower', models.FloatField(db_index=True)),
                ('re_upper', models.FloatField(db_index=True)),
                ('im_lower', models.FloatField(db_index=True)),
                ('im_upper', models.FloatField(db_index=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_numbers', to='db.table')),
            ],
        ),
    ]
