# Generated by Django 3.1.5 on 2021-05-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_numbercomplex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbercomplex',
            name='number_searchstring',
            field=models.TextField(db_index=True, max_length=128),
        ),
    ]
