# Generated by Django 3.2.3 on 2021-08-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20210510_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('author_and_email', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('author', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='tablecommit',
            name='contributor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='table_commits', to='db.contributor'),
        ),
    ]
