# Generated by Django 3.2.3 on 2021-08-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_alter_tablecommit_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecommit',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_commits', to='db.contributor'),
        ),
    ]
