# Generated by Django 3.2.3 on 2021-08-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_tablecommit_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablecommit',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tablecommit',
            name='author_email',
        ),
    ]
