# Generated by Django 3.2.3 on 2021-08-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20210828_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='table_commit_count',
            field=models.IntegerField(default=0),
        ),
    ]
