# Generated by Django 3.2.3 on 2021-08-29 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_contributor_table_commit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polynomial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_type', models.BinaryField(default=b'[', max_length=1)),
                ('number_string', models.TextField(db_index=True)),
                ('variable_count', models.IntegerField(db_index=True)),
                ('param', models.BinaryField(db_index=True, max_length=32)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polynomials', to='db.table')),
            ],
        ),
    ]
