# Generated by Django 3.2.3 on 2021-08-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_polynomial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polynomial',
            name='number_string_hash',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polynomial',
            name='number_string',
            field=models.TextField(),
        ),
    ]
