# Generated by Django 3.2.3 on 2021-08-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20210829_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polynomial',
            name='number_string_hash',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
