# Generated by Django 3.2.3 on 2021-10-23 00:21

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0015_alter_polynomial_number_string_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256, unique=True)),
                ('description', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanteds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
