# Generated by Django 3.2.3 on 2023-02-27 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20211023_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanted',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
