# Generated by Django 6.0.7 on 2026-08-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='polynomial',
            name='canonical_hash',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
    ]
