# Generated by Django 6.0.7 on 2026-08-03 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_tablethread_comment_tablerevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='head_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of', to='db.tablerevision'),
        ),
        migrations.AddField(
            model_name='table',
            name='reviewed_at_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_head_of', to='db.tablerevision'),
        ),
    ]
