# Generated by Django 6.0.7 on 2026-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_table_head_revision_table_reviewed_at_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='reviewed',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='numbercomplex',
            name='reviewed',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='numberpadic',
            name='reviewed',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='polynomial',
            name='reviewed',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
