# Generated by Django 6.0.7 on 2026-08-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_number_reviewed_numbercomplex_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='path',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True, unique=True),
        ),
    ]
