# Generated by Django 6.0.7 on 2026-08-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_alter_table_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('content', models.BinaryField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='db.tablerevision')),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='db.blob')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('revision', 'name'), name='one_blob_per_name_per_revision')],
            },
        ),
    ]
