# Generated by Django 6.0.7 on 2026-08-04 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_blob_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerevision',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='db.contributor'),
        ),
    ]
