# Generated by Django 6.0.7 on 2026-08-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_table_created_by_table_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerevision',
            name='run',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
