# Generated by Django 6.0.7 on 2026-08-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_tablelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
