# Generated by Django 6.0.7 on 2026-08-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_apikey_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=300)),
                ('showing', models.BooleanField(default=False)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
