# Generated by Django 6.0.7 on 2026-08-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_table_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='ready_for_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
