# Generated by Django 6.0.8 on 2026-09-11.
#
# Nothing here changes a table's contents or its shape. Django names an
# index after the model and a hash of its fields, and the two on `tablecost`
# were given their names by hand; `repeats` and `via` gained a `related_name`
# and a `choices` list, both of which live in Python and not in the schema.
#
# It exists because `makemigrations --check` failed on every deploy, and a
# check that always fails cannot report the one change that matters.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_table_metrics_sizes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tablecost',
            new_name='db_tablecos_model_69d99e_idx',
            old_name='db_tablecos_model_idx',
        ),
        migrations.RenameIndex(
            model_name='tablecost',
            new_name='db_tablecos_role_59020a_idx',
            old_name='db_tablecos_role_idx',
        ),
        migrations.AlterField(
            model_name='table',
            name='repeats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeated_by', to='db.table'),
        ),
        migrations.AlterField(
            model_name='tablerevision',
            name='via',
            field=models.CharField(blank=True, choices=[('web', 'the site'), ('api', 'the API directly'), ('package', 'the numberdb package'), ('import', 'an importer'), ('orm', 'the code directly')], max_length=16),
        ),
    ]
