# Generated by Django 6.0.8 on 2026-09-13.
#
# A cost row may now have no table, and says which campaign and which batch it
# belonged to instead. A fifth of everything this project has spent produced no
# table -- failed builds, ideas runs, triage -- and was counted and dropped
# because the row required one.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_index_names_and_field_kwargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecost',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tablecost',
            name='campaign',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='tablecost',
            name='table',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='costs', to='db.table'),
        ),
    ]
