# Generated by Django 6.0.7 on 2026-09-18 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_cost_without_a_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('started', models.DateTimeField(db_index=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('pipeline', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('pipeline_version', models.CharField(blank=True, default='', max_length=32)),
                ('pipeline_digest', models.CharField(blank=True, default='', max_length=64)),
                ('stage', models.CharField(blank=True, default='', max_length=32)),
                ('engine', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('effort', models.CharField(blank=True, default='', max_length=16)),
                ('session', models.CharField(blank=True, default='', max_length=80)),
                ('campaign', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('batch', models.CharField(blank=True, default='', max_length=80)),
                ('machine', models.CharField(blank=True, default='', max_length=64)),
                ('turns', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('tokens_in', models.BigIntegerField(blank=True, null=True)),
                ('tokens_cached', models.BigIntegerField(blank=True, null=True)),
                ('tokens_out', models.BigIntegerField(blank=True, null=True)),
                ('cost_by_model', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(blank=True, default='', max_length=16)),
                ('source', models.CharField(blank=True, db_index=True, default='run', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started',),
            },
        ),
        migrations.AddField(
            model_name='tablerevision',
            name='agent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='db.agentrun'),
        ),
    ]
