# Generated by Django 6.0.7 on 2026-09-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_agent_run'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablecost',
            unique_together={('table', 'model', 'role', 'campaign', 'batch')},
        ),
        migrations.AddIndex(
            model_name='tablecost',
            index=models.Index(fields=['campaign'], name='db_tablecos_campaig_22dd74_idx'),
        ),
    ]
