# Generated by Django 6.0.7 on 2026-09-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0050_cost_key_includes_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.IntegerField(db_index=True)),
                ('proposal', models.CharField(max_length=300)),
                ('worker', models.CharField(blank=True, default='', max_length=64)),
                ('claimed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['family', 'claimed_at'], name='db_proposal_family_4e15ff_idx')],
                'unique_together': {('family', 'proposal')},
            },
        ),
    ]
