#!/usr/bin/env bash
# Pull a verified database backup from the production server to this machine.
#
#     scripts/backup.sh                      # to ~/numberdb-backups
#     scripts/backup.sh /mnt/external        # somewhere else
#     REMOTE=linode scripts/backup.sh        # a different host
#
# Deliberately PULL rather than push. A push runs on the server, which means
# the server holds credentials for the backup store, and anything that can
# delete the server can delete its backups. Running from here, the server never
# has any reach into the copies, and the backups keep working when the hosting
# account itself is what went away.
#
# Run it unattended from the systemd user timer in scripts/systemd/, which
# catches up a missed run rather than skipping it -- the difference that
# matters on a laptop that is not on at three in the morning:
#
#     systemctl --user enable --now numberdb-backup.timer
#
# What this does NOT cover, on purpose:
#
#   * `.env`, which holds the secrets. It lives in Bitwarden, under the note
#     "numberdb.org production .env". Writing it here would scatter plaintext
#     credentials across every backup directory and every external drive.
#   * TLS certificates, which Let's Encrypt reissues in minutes.
#   * staticfiles and the numberdb-data checkout, both regenerated on deploy.
#
# The restore procedure is docs/runbooks/disaster-recovery.md, and it is worth
# rehearsing: an untested restore is a hypothesis, not a backup.
#
# ## Why this stores snapshots rather than files
#
# A dump is 232 MB, and a day changes about 20 MB of it. Measured over three
# consecutive dumps with content-defined chunking: 646 MB of dumps hold 286 MB
# of distinct chunks, and the third day contributed 19.8 MB. Sixty daily
# `.sql.gz` files are therefore not sixty days of safety; they are one day of
# safety, stored sixty times, for 4.2 GB.
#
# `restic` stores the chunks instead. The same sixty days cost a few hundred
# megabytes, `forget --keep-daily/weekly/monthly` replaces the hand-rolled
# `find -mtime` pruning, every snapshot is checksummed, and the repository can
# be copied off-site with one more command. It has to be fed the *plain* dump:
# compress first and every byte differs from yesterday, which is exactly the
# thing being avoided.
#
# Without `restic` installed, or without a repository password, this writes the
# old `numberdb-<stamp>.sql.gz` files and says how to switch. The verification
# is the same either way, and it is the part worth keeping.
#
# ## Why not keyframes and deltas, the way video does it
#
# Because content addressing is the same idea without the chain. Every snapshot
# here is *both* a full snapshot and a delta: it is a list of chunk references,
# and a chunk that any other snapshot already holds is not stored again. So the
# day's cost is the day's difference -- 19.8 MB in the measurement above -- with
# no periodic full re-upload of 232 MB to re-anchor it.
#
# What the chain costs, and this does not:
#
#   * a damaged delta breaks every snapshot after it until the next keyframe,
#     where a damaged chunk here breaks only the snapshots that name it;
#   * deleting an old snapshot in the middle means rebasing what depended on
#     it, where `forget --prune` drops the chunks nothing else references;
#   * restoring means replaying from the last keyframe rather than reading the
#     chunks a snapshot names.
#
# `duplicity` does full-plus-incremental chains, and the chain is why projects
# leave it. The thing that *would* shrink the daily difference further is not a
# keyframe -- it is not dumping the 203 MB of `db_number` at all, since the
# database rebuilds it from the revisions. See the runbook.
set -euo pipefail

REMOTE="${REMOTE:-linode}"
RPATH="${RPATH:-/opt/numberdb-website}"
DEST="${1:-$HOME/numberdb-backups}"

# How much history to keep. Sixty dailies was never the intent -- what anybody
# actually wants is "yesterday, last week, and some months back", which is what
# this says. Costs a few hundred megabytes rather than 4.2 GB.
KEEP_DAILY="${KEEP_DAILY:-7}"
KEEP_WEEKLY="${KEEP_WEEKLY:-8}"
KEEP_MONTHLY="${KEEP_MONTHLY:-12}"

# Only for the fallback path, where a file is a backup.
KEEP_DAYS="${KEEP_DAYS:-60}"

# The repository, and the key to it.
#
# Losing the password loses every backup in the repository: restic encrypts,
# and there is no recovery. It therefore belongs in Bitwarden beside the `.env`
# note, and this script refuses to invent one -- a secret generated by a timer
# at three in the morning is a secret nobody has.
# Which restic. The distribution's is 0.9.6 on this machine -- older than
# compression (0.14) and older than `copy` (0.10) -- so it would dedup and then
# store the chunks raw, which for the first snapshot is three times the .gz it
# replaces, and could not make the off-site copy at all. A current binary in
# ~/.local/bin wins, named outright because a timer's PATH is not a shell's.
RESTIC="${NUMBERDB_RESTIC:-}"
if [ -z "$RESTIC" ]; then
	if [ -x "$HOME/.local/bin/restic" ]; then
		RESTIC="$HOME/.local/bin/restic"
	else
		RESTIC=restic
	fi
fi

RESTIC_REPO="${NUMBERDB_RESTIC_REPO:-$DEST/repo}"
RESTIC_PASSWORD_FILE="${NUMBERDB_RESTIC_PASSWORD_FILE:-$HOME/.config/numberdb/restic-password}"

# The off-site copy, if there is one. Unset, everything below still works and
# says so once; a backup that exists only on this laptop is better than no
# backup, and worse than two.
#
#     NUMBERDB_S3_REPO=s3:s3.eu-central-1.amazonaws.com/numberdb-backups
#
# Credentials come from a file rather than the environment, because the timer
# has neither an ssh agent nor an AWS SSO session: an expired `aws login` must
# not be able to stop the backup. docs/runbooks/disaster-recovery.md has the
# bucket and the IAM policy to create.
S3_REPO="${NUMBERDB_S3_REPO:-}"
S3_ENV="${NUMBERDB_S3_ENV:-$HOME/.config/numberdb/s3-env}"

#A dump smaller than this means something went wrong: an empty database, a
#permission error swallowed by the pipe, or pg_dump writing its complaint to
#stdout. The real dump is around 230 MB uncompressed; 1 MB is far below
#anything plausible and far above an error message.
MIN_BYTES="${MIN_BYTES:-1000000}"

#An unattended run has no ssh agent, so the key has to be named outright.
#Without this the timer fails with "Permission denied (publickey)" while the
#same command typed by hand works -- the agent being the whole difference, and
#the least obvious one to look for.
SSH_KEY="${SSH_KEY:-}"
ssh_opts=(-o BatchMode=yes -o ClearAllForwardings=yes)
[ -n "$SSH_KEY" ] && ssh_opts+=(-o IdentitiesOnly=yes -i "$SSH_KEY")

stamp="$(date +%Y%m%d-%H%M%S)"
mkdir -p "$DEST"

#A fixed path rather than a random temporary one, so that every snapshot names
#the same file and `restic dump latest numberdb.sql` works without looking up
#which directory that night's run happened to use.
staging="$DEST/.staging"
plain="$staging/numberdb.sql"
rm -rf "$staging"
mkdir -p "$staging"
trap 'rm -rf "$staging"' EXIT

echo "[$(date -Iseconds)] backing up $REMOTE:$RPATH"

#-T because there is no terminal; without it docker allocates a TTY and
#corrupts the dump with carriage returns that psql later refuses to read.
#ClearAllForwardings: the linode host in ~/.ssh/config carries a RemoteForward
#with ExitOnForwardFailure, so a second connection aborts rather than sharing
#the port. A backup that fails because a terminal is open is a backup that
#fails on exactly the busy days.
ssh "${ssh_opts[@]}" "$REMOTE" \
	"cd $RPATH && docker compose exec -T db pg_dump -U u_numberdb --clean --if-exists numberdb" \
	> "$plain"

size=$(stat -c%s "$plain" 2>/dev/null || stat -f%z "$plain")
if [ "$size" -lt "$MIN_BYTES" ]; then
	echo "FAILED: dump is only $size bytes, expected at least $MIN_BYTES" >&2
	mv "$plain" "$DEST/numberdb-$stamp.sql.SUSPECT"
	exit 1
fi

#Truncation, checked at the source rather than inferred. `pg_dump` ends with a
#line saying so, and a transfer that stopped early does not have it -- which is
#a stronger statement than "the gzip container is intact", since a dump can be
#cut off cleanly at a block boundary and still decompress.
if ! tail -c 200 "$plain" | grep -q 'PostgreSQL database dump complete'; then
	echo "FAILED: $plain does not end with pg_dump's completion line" >&2
	mv "$plain" "$DEST/numberdb-$stamp.sql.TRUNCATED"
	exit 1
fi

#And that it is actually this database, not an error page or an empty schema.
present=$(grep -oE '^CREATE TABLE public\.[a-z_]+' "$plain" | sed 's/.*\.//' | sort -u)
for table in db_table db_number auth_user; do
	if ! printf '%s\n' "$present" | grep -qx "$table"; then
		echo "FAILED: the dump contains no table $table" >&2
		mv "$plain" "$DEST/numberdb-$stamp.sql.SUSPECT"
		exit 1
	fi
done
echo "  verified: $(numfmt --to=iec "$size" 2>/dev/null || echo "$size bytes"), $(printf '%s\n' "$present" | wc -l) tables"

# Is the snapshot path available? Three separate things can be missing, and
# each has a different one-line answer, so say which.
restic_ready() {
	if ! command -v "$RESTIC" >/dev/null 2>&1; then
		echo "  (storing a compressed copy; install restic to store snapshots instead)"
		return 1
	fi
	#Version, not just presence. 0.9.6 would run every command below except
	#`copy` and quietly store everything uncompressed, which looks like it
	#worked and costs three times as much.
	have=$("$RESTIC" version 2>/dev/null | awk '{print $2}')
	if [ "$(printf '%s\n0.14\n' "$have" | sort -V | head -1)" != "0.14" ]; then
		echo "  (storing a compressed copy; restic $have is older than 0.14," >&2
		echo "   which is where compression and 'copy' arrive. A current one:" >&2
		echo "     curl -sL https://github.com/restic/restic/releases/latest \\" >&2
		echo "       | grep -o 'download/[^\"]*linux_amd64.bz2'  # into ~/.local/bin" >&2
		return 1
	fi
	if [ ! -s "$RESTIC_PASSWORD_FILE" ]; then
		echo "  (storing a compressed copy; no repository password at $RESTIC_PASSWORD_FILE)" >&2
		echo "   make one, and put it in Bitwarden before it holds anything:" >&2
		echo "     mkdir -p \"\$(dirname $RESTIC_PASSWORD_FILE)\"" >&2
		echo "     openssl rand -base64 32 > $RESTIC_PASSWORD_FILE && chmod 600 $RESTIC_PASSWORD_FILE" >&2
		return 1
	fi
	return 0
}

if restic_ready; then
	export RESTIC_PASSWORD_FILE
	export RESTIC_REPOSITORY="$RESTIC_REPO"
	#Compression is the reason to be on 0.14 or later; on an older one this
	#still dedups, just without the second factor.
	export RESTIC_COMPRESSION="${RESTIC_COMPRESSION:-max}"

	if ! "$RESTIC" cat config >/dev/null 2>&1; then
		echo "  initialising $RESTIC_REPO"
		"$RESTIC" init >/dev/null
	fi

	#`--host` fixed, so that running this from a second machine does not start
	#a second lineage of snapshots that `forget` then keeps separately.
	"$RESTIC" backup --quiet --host numberdb --tag database "$plain"
	"$RESTIC" forget --quiet --prune \
		--host numberdb --tag database \
		--keep-daily "$KEEP_DAILY" \
		--keep-weekly "$KEEP_WEEKLY" \
		--keep-monthly "$KEEP_MONTHLY"

	#Structure only: cheap, and catches the repository being damaged by a full
	#disk or an interrupted prune. Reading every byte back is `restic check
	#--read-data`, which belongs in the rehearsal, not in a nightly timer.
	"$RESTIC" check --quiet || echo "  WARNING: restic check reported a problem" >&2

	kept=$("$RESTIC" snapshots --host numberdb --tag database --json 2>/dev/null \
	       | grep -o '"time"' | wc -l)
	echo "  $kept snapshot(s) in $RESTIC_REPO, $(du -sh "$RESTIC_REPO" 2>/dev/null | cut -f1) on disk"

	if [ -n "$S3_REPO" ]; then
		#A copy rather than a second backup: the same chunks, so the upload is
		#the day's delta and not the whole dump, and the off-site repository is
		#restorable on its own.
		[ -f "$S3_ENV" ] && . "$S3_ENV"
		if "$RESTIC" -r "$S3_REPO" cat config >/dev/null 2>&1 \
		   || "$RESTIC" -r "$S3_REPO" init >/dev/null 2>&1; then
			if "$RESTIC" -r "$S3_REPO" copy --quiet --from-repo "$RESTIC_REPO" \
			   --host numberdb --tag database; then
				"$RESTIC" -r "$S3_REPO" forget --quiet --prune \
					--host numberdb --tag database \
					--keep-daily "$KEEP_DAILY" \
					--keep-weekly "$KEEP_WEEKLY" \
					--keep-monthly "$KEEP_MONTHLY"
				echo "  copied off-site to $S3_REPO"
			else
				#Never fatal. The local snapshot is already made and verified,
				#and a network fault should not be recorded as "no backup".
				echo "  WARNING: the off-site copy did not go through" >&2
			fi
		else
			echo "  WARNING: cannot reach $S3_REPO (credentials in $S3_ENV?)" >&2
		fi
	else
		echo "  (no off-site copy configured; see NUMBERDB_S3_REPO in this file)"
	fi
else
	out="$DEST/numberdb-$stamp.sql.gz"
	#Written under a name nothing looks for, and renamed only once it is
	#whole. A run killed mid-write -- a laptop suspending at three in the
	#morning -- used to leave a `numberdb-*.sql.gz` that was a perfectly valid
	#gzip of nothing: two of the first fifty-one here were 20 and 980 bytes,
	#and the retention policy dutifully kept one as a daily.
	gzip -9 -c "$plain" > "$out.partial"
	if ! gzip -t "$out.partial" 2>/dev/null; then
		echo "FAILED: $out.partial is not valid gzip" >&2
		exit 1
	fi
	mv "$out.partial" "$out"
	echo "  ok: $out"

	#Retention. Old dumps are deleted only after the new one has been verified
	#above, so a run that fails leaves yesterday's backup untouched.
	deleted=$(find "$DEST" -maxdepth 1 -name 'numberdb-*.sql.gz' -mtime "+$KEEP_DAYS" -print -delete | wc -l)
	[ "$deleted" -gt 0 ] && echo "  pruned $deleted backup(s) older than $KEEP_DAYS days"

	count=$(find "$DEST" -maxdepth 1 -name 'numberdb-*.sql.gz' | wc -l)
	echo "  $count backup(s) in $DEST, $(du -sh "$DEST" 2>/dev/null | cut -f1) total"
fi
